# Generated by Django 2.2.3 on 2020-03-22 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Top_posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_top', models.ImageField(upload_to='media/images')),
                ('summary_top', models.CharField(max_length=100)),
            ],
        ),
    ]
