# Generated by Django 2.2.3 on 2020-03-22 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Top_posts',
            new_name='TopPosts',
        ),
    ]
