# Generated by Django 2.2.3 on 2020-03-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20200322_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='topposts',
            name='top_post_heading',
            field=models.CharField(default='', editable=False, max_length=50),
        ),
    ]
