# Generated by Django 2.2.3 on 2020-03-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_topposts_top_post_heading'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='', editable=False, max_length=50)),
                ('Description', models.CharField(default='', editable=False, max_length=500)),
                ('Images', models.ImageField(upload_to='images')),
                ('Date', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='topposts',
            name='img_top',
            field=models.ImageField(upload_to='images'),
        ),
    ]
