# Generated by Django 2.2.3 on 2020-03-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20200322_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='Content',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='projects',
            name='Description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='projects',
            name='Title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='topposts',
            name='top_post_heading',
            field=models.CharField(default='', max_length=50),
        ),
    ]
